---
ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios
ansible_become: true
ansible_become_method: enable

ansible_user: "{{ lookup('env', 'LAB_ANSIBLE_USER') }}"
ansible_password: "{{ lookup('env', 'LAB_ANSIBLE_PASSWORD') }}"
ansible_become_password: "{{ lookup('env', 'LAB_ENABLE_PASSWORD') }}"

ospf_process_id: 10
bgp_as: 65000
