---
hostname: R2
router_id: 2.2.2.2
loopback0_ip: 2.2.2.2
loopback0_mask: 255.255.255.255

interfaces:
  - name: GigabitEthernet0/1
    description: TO_R1
    ip: 10.0.12.2
    mask: 255.255.255.252
    ospf: true
  - name: GigabitEthernet0/2
    description: TO_R4
    ip: 10.0.24.1
    mask: 255.255.255.252
    ospf: true

bgp_neighbors:
  - neighbor_ip: 1.1.1.1
    remote_as: 65000
  - neighbor_ip: 3.3.3.3
    remote_as: 65000
  - neighbor_ip: 4.4.4.4
    remote_as: 65000
  - neighbor_ip: 5.5.5.5
    remote_as: 65000
